from copy import deepcopy


SECURITY_MODEL = {
    "version": "2.0",
    "scope": "覆盖外部情报采集、模型分析、人工复核、正式入库与 RAG 知识复用链路。",
    "business_flow": [
        "外部数据源",
        "抓取与标准化",
        "情报池",
        "相关性判断",
        "字段抽取与评分",
        "人工复核",
        "正式漏洞库",
        "RAG 检索与回答",
    ],
    "architecture_nodes": [
        {"id": "browser", "label": "Web 前端", "layer": "交互层", "description": "看板、情报复核、漏洞维护与知识检索"},
        {"id": "api", "label": "FastAPI", "layer": "服务层", "description": "请求校验、权限判断和业务编排"},
        {"id": "services", "label": "领域服务", "layer": "服务层", "description": "采集、分析、情报、漏洞与 RAG 服务"},
        {"id": "worker", "label": "Celery Worker", "layer": "任务层", "description": "执行采集、分析、复核辅助与通知任务"},
        {"id": "scheduler", "label": "Celery Beat", "layer": "任务层", "description": "按计划触发数据源采集"},
        {"id": "redis", "label": "Redis", "layer": "数据层", "description": "任务队列与调度消息"},
        {"id": "database", "label": "PostgreSQL", "layer": "数据层", "description": "情报、漏洞、审计记录与向量数据"},
        {"id": "sources", "label": "外部情报源", "layer": "外部依赖", "description": "GitHub Advisory、RSS 与厂商公告"},
        {"id": "llm", "label": "模型服务", "layer": "外部依赖", "description": "OpenAI、DeepSeek 或本地 Mock"},
        {"id": "embedding", "label": "Embedding", "layer": "模型层", "description": "FastEmbed 多语言语义向量"},
    ],
    "architecture_edges": [
        {"source": "browser", "target": "api", "label": "REST / JSON"},
        {"source": "api", "target": "services", "label": "业务调用"},
        {"source": "services", "target": "database", "label": "读写与检索"},
        {"source": "api", "target": "redis", "label": "任务投递"},
        {"source": "scheduler", "target": "redis", "label": "定时调度"},
        {"source": "redis", "target": "worker", "label": "任务消费"},
        {"source": "worker", "target": "services", "label": "异步执行"},
        {"source": "sources", "target": "services", "label": "不可信内容"},
        {"source": "services", "target": "llm", "label": "提示与上下文"},
        {"source": "services", "target": "embedding", "label": "文本向量化"},
    ],
    "trust_boundaries": [
        {
            "id": "external",
            "title": "不可信输入域",
            "trust_level": "untrusted",
            "description": "内容可被攻击者控制，不能作为系统指令或授权依据。",
            "assets": ["网页与 RSS 内容", "Advisory 原文", "用户查询"],
        },
        {
            "id": "application",
            "title": "应用受控域",
            "trust_level": "controlled",
            "description": "负责校验、隔离、审计和人工复核，是主要安全控制边界。",
            "assets": ["FastAPI", "Celery / Redis", "漏洞库与向量索引", "审计记录"],
        },
        {
            "id": "provider",
            "title": "第三方处理域",
            "trust_level": "third_party",
            "description": "发送内容前需要最小化和脱敏，返回结果仍按不可信数据处理。",
            "assets": ["外部模型 API", "模型请求上下文", "模型输出"],
        },
    ],
    "threats": [
        {
            "id": "T1", "category": "欺骗", "title": "伪造情报来源",
            "scenario": "攻击者伪造来源或复用可信域名内容，引导平台接收虚假漏洞情报。",
            "impact": "错误情报进入分析链路，降低数据可信度并误导处置。",
            "current_controls": ["保留来源 URL", "保存原始文档", "发布前人工复核"],
            "recommended_controls": ["来源域白名单", "内容哈希", "来源信誉评分"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T2", "category": "篡改", "title": "间接提示注入",
            "scenario": "恶意公告把攻击指令伪装成正文，操纵相关性判断、字段抽取或 RAG 回答。",
            "impact": "分析结论被污染，可能诱导数据泄露或越权操作。",
            "current_controls": ["原始材料与正式库隔离", "Schema 校验", "人工复核"],
            "recommended_controls": ["指令与证据边界标记", "注入特征检测", "引用一致性校验"],
            "priority": "严重", "status": "部分实施",
        },
        {
            "id": "T3", "category": "抵赖", "title": "关键操作抵赖",
            "scenario": "操作者否认发布、驳回或合并情报的操作。",
            "impact": "无法还原错误记录的责任与变更路径。",
            "current_controls": ["Review Action", "分析任务记录", "来源血缘链"],
            "recommended_controls": ["记录前后值", "全链路 Request ID", "限制审计日志修改"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T4", "category": "信息泄露", "title": "模型上下文泄露",
            "scenario": "内部漏洞、密钥或环境信息被拼入第三方模型请求或返回给无权用户。",
            "impact": "敏感数据和访问凭据泄露。",
            "current_controls": ["密钥使用环境变量", "RAG 只检索漏洞库"],
            "recommended_controls": ["出站字段分级与脱敏", "最小化上下文", "密钥轮换"],
            "priority": "严重", "status": "部分实施",
        },
        {
            "id": "T5", "category": "拒绝服务", "title": "资源与额度耗尽",
            "scenario": "超长文本、高频检索或任务重试耗尽模型额度、CPU、内存和队列。",
            "impact": "采集、分析与问答服务不可用，产生异常费用。",
            "current_controls": ["请求字段限长", "异步任务", "模型超时与重试"],
            "recommended_controls": ["分级限流", "正文大小上限", "熔断与死信队列", "预算告警"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T6", "category": "权限提升", "title": "演示身份头伪造",
            "scenario": "攻击者伪造角色请求头，执行发布、合并或配置修改。",
            "impact": "未授权修改正式漏洞数据和系统配置。",
            "current_controls": ["服务端角色检查", "关键接口角色要求"],
            "recommended_controls": ["正式身份认证", "不可伪造会话", "关键操作二次确认"],
            "priority": "严重", "status": "规划中",
        },
        {
            "id": "T7", "category": "篡改", "title": "向量库数据投毒",
            "scenario": "大量相似恶意片段进入漏洞库，长期操纵召回排序与回答。",
            "impact": "知识检索持续返回被污染的证据和结论。",
            "current_controls": ["情报池隔离", "合并候选", "人工复核"],
            "recommended_controls": ["来源配额", "异常相似簇检测", "索引版本与回滚"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T8", "category": "信息泄露", "title": "越权知识检索",
            "scenario": "攻击者通过组合查询枚举库内记录，或在未来多租户场景跨边界检索。",
            "impact": "敏感漏洞、内部文档或租户数据泄露。",
            "current_controls": ["回答展示引用记录", "限制召回数量"],
            "recommended_controls": ["检索前记录级授权", "敏感查询审计", "强制租户过滤"],
            "priority": "严重", "status": "规划中",
        },
        {
            "id": "T9", "category": "篡改", "title": "危险工具指令",
            "scenario": "模型生成的 SQL、URL 或工具参数被下游直接执行。",
            "impact": "导致数据修改、外部请求或非授权工具操作。",
            "current_controls": ["当前 RAG 仅生成文本", "生成与执行隔离"],
            "recommended_controls": ["工具允许列表", "参数校验", "高风险动作人工批准"],
            "priority": "高", "status": "已实施",
        },
        {
            "id": "T10", "category": "供应链", "title": "依赖与模型污染",
            "scenario": "依赖包、容器镜像或 Embedding 模型被替换或携带漏洞。",
            "impact": "数据外传、模型行为变化或服务被植入恶意代码。",
            "current_controls": ["依赖锁文件", "固定基础镜像版本"],
            "recommended_controls": ["镜像 Digest", "SBOM", "模型文件校验", "持续依赖扫描"],
            "priority": "中", "status": "部分实施",
        },
    ],
    "rag_controls": [
        "只让经复核的正式漏洞记录参与检索",
        "将证据片段视为数据而非指令",
        "限制召回数量、片段长度与总上下文",
        "回答引用必须映射到本次召回记录",
        "先做记录级权限过滤，再执行语义检索",
        "模型回答不得直接触发工具或数据库写入",
        "记录查询、命中记录、模型版本与耗时",
        "证据不足或模型异常时降级为检索结果",
    ],
    "release_baseline": [
        "用正式认证与 RBAC 替换演示型角色请求头",
        "限制生产环境 CORS 来源并关闭不需要的调试入口",
        "为正文、上下文、模型调用和任务重试设置硬上限",
        "确保只有复核通过的记录进入 RAG 索引",
        "对发送到第三方模型的字段做最小化和脱敏",
    ],
}


def get_security_model() -> dict:
    return deepcopy(SECURITY_MODEL)
