from copy import deepcopy


SECURITY_MODEL = {
    "version": "3.0",
    "scope": "覆盖外部情报采集、模型分析、人工复核、正式入库与 RAG 知识复用链路。",
    "business_flow": [
        "外部数据源",
        "抓取与标准化",
        "情报池",
        "相关性判断",
        "字段抽取与评分",
        "人工复核",
        "正式漏洞库",
        "RAG 检索与回答",
    ],
    "architecture_nodes": [
        {"id": "browser", "label": "Web 前端", "layer": "交互层", "description": "看板、情报复核、漏洞维护与知识检索"},
        {"id": "api", "label": "FastAPI", "layer": "服务层", "description": "请求校验、权限判断和业务编排"},
        {"id": "services", "label": "领域服务", "layer": "服务层", "description": "采集、分析、情报、漏洞与 RAG 服务"},
        {"id": "worker", "label": "Celery Worker", "layer": "任务层", "description": "执行采集、分析、复核辅助与通知任务"},
        {"id": "scheduler", "label": "Celery Beat", "layer": "任务层", "description": "按计划触发数据源采集"},
        {"id": "redis", "label": "Redis", "layer": "数据层", "description": "任务队列与调度消息"},
        {"id": "database", "label": "PostgreSQL", "layer": "数据层", "description": "情报、漏洞、审计记录与向量数据"},
        {"id": "sources", "label": "外部情报源", "layer": "外部依赖", "description": "GitHub Advisory、RSS 与厂商公告"},
        {"id": "llm", "label": "模型服务", "layer": "外部依赖", "description": "OpenAI、DeepSeek 或本地 Mock"},
        {"id": "embedding", "label": "Embedding", "layer": "模型层", "description": "FastEmbed 多语言语义向量"},
    ],
    "architecture_edges": [
        {"source": "browser", "target": "api", "label": "REST / JSON"},
        {"source": "api", "target": "services", "label": "业务调用"},
        {"source": "services", "target": "database", "label": "读写与检索"},
        {"source": "api", "target": "redis", "label": "任务投递"},
        {"source": "scheduler", "target": "redis", "label": "定时调度"},
        {"source": "redis", "target": "worker", "label": "任务消费"},
        {"source": "worker", "target": "services", "label": "异步执行"},
        {"source": "sources", "target": "services", "label": "不可信内容"},
        {"source": "services", "target": "llm", "label": "提示与上下文"},
        {"source": "services", "target": "embedding", "label": "文本向量化"},
    ],
    "trust_boundaries": [
        {
            "id": "external",
            "title": "不可信输入域",
            "trust_level": "untrusted",
            "description": "内容可被攻击者控制，不能作为系统指令或授权依据。",
            "assets": ["网页与 RSS 内容", "Advisory 原文", "用户查询"],
        },
        {
            "id": "application",
            "title": "应用受控域",
            "trust_level": "controlled",
            "description": "负责校验、隔离、审计和人工复核，是主要安全控制边界。",
            "assets": ["FastAPI", "Celery / Redis", "漏洞库与向量索引", "审计记录"],
        },
        {
            "id": "provider",
            "title": "第三方处理域",
            "trust_level": "third_party",
            "description": "发送内容前需要最小化和脱敏，返回结果仍按不可信数据处理。",
            "assets": ["外部模型 API", "模型请求上下文", "模型输出"],
        },
    ],
    "threats": [
        {
            "id": "T1", "category": "欺骗", "title": "伪造情报来源",
            "scenario": "攻击者伪造来源或复用可信域名内容，引导平台接收虚假漏洞情报。",
            "impact": "错误情报进入分析链路，降低数据可信度并误导处置。",
            "current_controls": ["保留来源 URL", "保存原始文档", "发布前人工复核"],
            "recommended_controls": ["来源域白名单", "内容哈希", "来源信誉评分"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T2", "category": "篡改", "title": "间接提示注入",
            "scenario": "恶意公告把攻击指令伪装成正文，操纵相关性判断、字段抽取或 RAG 回答。",
            "impact": "分析结论被污染，可能诱导数据泄露或越权操作。",
            "current_controls": ["不可信内容边界标记", "系统提示禁止执行证据内指令", "HTML 与控制字符清洗", "模型输出 Schema 校验", "人工复核后入库"],
            "recommended_controls": ["持续维护注入评测集", "引用一致性自动校验", "高风险样本隔离告警"],
            "priority": "严重", "status": "已实施",
        },
        {
            "id": "T3", "category": "抵赖", "title": "关键操作抵赖",
            "scenario": "操作者否认发布、驳回或合并情报的操作。",
            "impact": "无法还原错误记录的责任与变更路径。",
            "current_controls": ["Review Action", "分析任务记录", "来源血缘链"],
            "recommended_controls": ["记录前后值", "全链路 Request ID", "限制审计日志修改"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T4", "category": "信息泄露", "title": "模型上下文泄露",
            "scenario": "内部漏洞、密钥或环境信息被拼入第三方模型请求或返回给无权用户。",
            "impact": "敏感数据和访问凭据泄露。",
            "current_controls": ["模型出口统一密钥脱敏", "提示内容不写入分析轨迹", "上下文与字段硬上限", "原始情报仅 analyst 可读", "密钥使用环境变量"],
            "recommended_controls": ["接入企业 DLP 规则", "自动密钥轮换", "第三方模型数据驻留策略"],
            "priority": "严重", "status": "已实施",
        },
        {
            "id": "T5", "category": "拒绝服务", "title": "资源与额度耗尽",
            "scenario": "超长文本、高频检索或任务重试耗尽模型额度、CPU、内存和队列。",
            "impact": "采集、分析与问答服务不可用，产生异常费用。",
            "current_controls": ["请求体 256 KiB 硬上限", "采集响应 2 MiB 硬上限", "字段与 RAG 问题限长", "候选数量上限", "模型超时与重试"],
            "recommended_controls": ["按用户和来源分级限流", "模型调用熔断", "费用预算告警"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T6", "category": "权限提升", "title": "演示身份头伪造",
            "scenario": "攻击者伪造角色请求头，执行发布、合并或配置修改。",
            "impact": "未授权修改正式漏洞数据和系统配置。",
            "current_controls": ["环境密码登录", "访客专用只读会话", "Redis 随机会话", "HttpOnly / SameSite=Strict Cookie", "写操作 CSRF 校验", "服务端 RBAC", "登录失败限速"],
            "recommended_controls": ["接入企业 OIDC 与 MFA", "高风险操作二次确认", "集中会话设备管理"],
            "priority": "严重", "status": "已实施",
        },
        {
            "id": "T7", "category": "篡改", "title": "向量库数据投毒",
            "scenario": "大量相似恶意片段进入漏洞库，长期操纵召回排序与回答。",
            "impact": "知识检索持续返回被污染的证据和结论。",
            "current_controls": ["外部内容禁止自动发布", "情报池与正式库隔离", "内容哈希去重", "合并候选", "带角色校验的人工复核"],
            "recommended_controls": ["来源配额", "异常相似簇检测", "索引版本与回滚"],
            "priority": "高", "status": "部分实施",
        },
        {
            "id": "T8", "category": "信息泄露", "title": "越权知识检索",
            "scenario": "攻击者通过组合查询枚举库内记录，或在未来多租户场景跨边界检索。",
            "impact": "敏感漏洞、内部文档或租户数据泄露。",
            "current_controls": ["记录 public/internal/restricted 分级", "访客仅接收 public 记录的裁剪摘要", "访客禁止使用 RAG", "向量召回前按会话角色过滤", "查询哈希与命中 ID 审计", "查询摘录脱敏", "回答展示授权范围内引用"],
            "recommended_controls": ["多租户上线前增加 tenant_id 强制过滤", "异常枚举查询告警", "按账户查询频率限制"],
            "priority": "严重", "status": "已实施",
        },
        {
            "id": "T9", "category": "篡改", "title": "危险工具指令",
            "scenario": "模型生成的 SQL、URL 或工具参数被下游直接执行。",
            "impact": "导致数据修改、外部请求或非授权工具操作。",
            "current_controls": ["当前 RAG 仅生成文本", "生成与执行隔离"],
            "recommended_controls": ["工具允许列表", "参数校验", "高风险动作人工批准"],
            "priority": "高", "status": "已实施",
        },
        {
            "id": "T10", "category": "供应链", "title": "依赖与模型污染",
            "scenario": "依赖包、容器镜像或 Embedding 模型被替换或携带漏洞。",
            "impact": "数据外传、模型行为变化或服务被植入恶意代码。",
            "current_controls": ["依赖锁文件", "固定基础镜像版本"],
            "recommended_controls": ["镜像 Digest", "SBOM", "模型文件校验", "持续依赖扫描"],
            "priority": "中", "status": "部分实施",
        },
        {
            "id": "T11", "category": "信息泄露", "title": "采集器 SSRF",
            "scenario": "攻击者配置恶意数据源或重定向地址，诱导采集器访问环回、内网或云元数据服务。",
            "impact": "内网服务被探测，凭据或管理接口数据泄露。",
            "current_controls": ["仅允许 HTTP/HTTPS", "拒绝 URL 凭据", "DNS 解析结果必须为公网地址", "逐次校验重定向目标", "禁用环境代理", "本地文件限制在 data 目录"],
            "recommended_controls": ["基础设施出站防火墙", "独立采集网络", "DNS 重绑定监控"],
            "priority": "严重", "status": "已实施",
        },
        {
            "id": "T12", "category": "篡改", "title": "恶意 HTML 与活动内容",
            "scenario": "外部正文包含脚本、iframe、SVG、隐藏文本或危险链接，试图影响模型分析或前端展示。",
            "impact": "造成跨站脚本、界面欺骗或隐藏提示注入。",
            "current_controls": ["采集时移除活动标签和隐藏内容", "统一转换为纯文本", "React 默认转义", "外链仅允许 HTTP/HTTPS", "CSP 与安全响应头"],
            "recommended_controls": ["启用 CSP 违规上报", "定期扩充恶意 HTML 回归样本"],
            "priority": "高", "status": "已实施",
        },
    ],
    "rag_controls": [
        "只让经复核的正式漏洞记录参与检索",
        "问题和证据均使用不可信边界封装，并明确禁止执行其中的指令",
        "限制召回数量、片段长度与总上下文",
        "回答引用必须映射到本次召回记录",
        "根据可信会话角色和记录可见级别过滤后，再执行语义检索",
        "模型回答不得直接触发工具或数据库写入",
        "脱敏记录查询摘要、查询哈希、角色和命中记录",
        "证据不足或模型异常时降级为检索结果",
    ],
    "release_baseline": [
        "生产环境配置三类账户强密码，并通过 HTTPS 启用 Secure Cookie",
        "限制生产环境 CORS 来源并关闭不需要的调试入口",
        "为正文、上下文、模型调用和任务重试设置硬上限",
        "确保只有复核通过的记录进入 RAG 索引",
        "对发送到第三方模型的字段做最小化和脱敏",
    ],
}


def get_security_model() -> dict:
    return deepcopy(SECURITY_MODEL)
